"""Graph -> .topo emission.

This is the deterministic mapping committed to by design — fixed rules
that produce ``.topo``, never magic inference:

  - handler A's output feeds handler B's input  -> edge A -> B
  - logic chain A -> B -> C                      -> flow with those edges
  - the flow's stage topology is left to core PipelineAnalysis; the
    emitter only states edges, never stage numbers (handler/flow spec
    §7a: flow body accepts pipeline edges only)

The output is human-readable and hand-editable by construction — that
is the decisive round-trip constraint, so the emitter favours a stable,
obvious layout over compactness.
"""

from __future__ import annotations

from ._graph import Graph

# Scalar aliases the Python host binds, matching topo-init's preamble so
# emitted .topo consumes the same stdlib vocabulary the rest of the
# toolchain expects.
_PREAMBLE = (
    "using int = std::python::int;\n"
    "using float = std::python::float;\n"
    "using bool = std::python::bool;\n"
    "using str = std::python::str;\n"
)


def emit_topo(graph: Graph) -> str:
    lines = [
        "// Generated by topo-app (Python). Human-readable and round-trip",
        "// safe: editing this file and reading it back yields the same",
        "// logic graph. Hand edits survive; this is a view, not an IR.",
        "",
        _PREAMBLE.rstrip("\n"),
        "",
        f"namespace {graph.namespace} {{",
        "  public:",
    ]
    for h in graph.handlers:
        lines.append(f"    {h.signature()}")
    if graph.flow is not None:
        lines.append("")
        lines.append(f"    flow {graph.flow.name} {{")
        for e in graph.flow.edges:
            tgt = "void" if e.is_terminal else e.target
            lines.append(f"      {e.source} -> {tgt};")
        lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)
